name: Update Publications

on:
  schedule:
    # Runs at 03:00 on the first day of each month
    - cron: '0 3 1 * *'
  workflow_dispatch:  # allows manual trigger
  push:

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml unidecode
      - name: Get last run date
        run: |
          last_run_iso=$(gh run list --workflow "Update Publications" --status success --limit 1 --json createdAt --jq '.[0].createdAt'  2>/dev/null || echo "")
          if [ -z "$last_run_iso" ]; then
            last_run_iso="2019-01-01T00:00:00Z"   # fallback default
          fi
          last_run=$(date -u -d "$last_run_iso" +"%Y-%m-%d")
          echo "LAST_RUN=$last_run" >> $GITHUB_ENV
      - name: Create branch
        run: |
          branch_name="update-publications-$(date +'%Y%m%d')"
          git checkout -b $branch_name
          echo "branch_name=${branch_name}" >> $GITHUB_ENV
      - name: Run publication update script
        run: python scripts/update_publications.py
      - name: Commit changes
        run: |
          git add content/publication
          git commit -m "Automated update of publications" || echo "No changes to commit"
      - name: Push branch
        run: git push origin HEAD
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          gh pr create \
            --title "Update publications" \
            --body "Automated update of publications since ${LAST_RUN}." \
            --base main \
            --head $branch_name

