name: site-deploy
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: data
          path: public
      - name: Build site
        run: |
          rm -rf public/*
          docker run -i -v "$(pwd):/src" klakegg/hugo:0.81.0-ext-alpine-ci
          echo 'google-site-verification: googleb7e4372583e95220.html' > public/googleb7e4372583e95220.html
      - name: Deploy site
        run: |
          cd public
          git config user.email "github-commit-hook@example.com"
          git config user.name "Github Commit Hook"
          git add -A .
          git commit -a -m "Update to match ${GITHUB_SHA}"
          git push -f
